export const VIDEO_CATEGORIES = [
  { value: "all", label: "All" },
  { value: "singer", label: "Singer" },
  { value: "dancer", label: "Dancer" },
  { value: "musicians", label: "Musician" },
  { value: "anchor", label: "Anchor" },
  { value: "DJ", label: "DJ" },
  { value: "band", label: "Live Band " },
  { value: "comedian", label: "Comedian" },
  { value: "magician", label: "Magician" },
  { value: "actor", label: "Actor" },
  { value: "mimicry", label: "Mimicry" },
  { value: "specialAct", label: "Special Act Performer" },
  { value: "spiritual", label: "Spiritual" },
  { value: "kidsEntertainer", label: "Kids Entertainer" },
];
